### PR TITLE
Add ability to pass non-default decls and atrules instead of default …

### PR DESCRIPTION
**Pull request by scherbenokk**
…values

### CODE REVIEW

**Comment by crimx** [comment]
Hi! Thanks for the PR. Is there a reason why one would do that?

**Comment by crimx** [comment]
This is a breaking change. I may need more info about why.

**Comment by scherbenokk** [comment]
Yes, I can update the version of the package. I need to set !important flag for animation properties, so this changes can help me.

**Comment by crimx** [comment]
> I need to set !important flag for animation properties

Yeah @scherbenokk I know you want to do this but why?

**Comment by scherbenokk** [comment]
I'm developing a chat widget for different websites, so I should be sure that the widget styles won't be overridden by any site styles. Just to insure.

**Comment by scherbenokk** [comment]
If it's not necessary to your package, that's not a problem) I'll solve it manually, it just like additional ability

**Comment by scherbenokk** [comment]
it seems that we shouldn't override atrules(or keyframes in particular), but we can allow to override declarations

**Comment by crimx** [comment]
Hi @scherbenokk I think "Just to insure" is not good enough for such breaking change. You might want to take a second thought if this is necessary. Maybe put up a small example that can prove it?

Firstly mixing `!important` with `animation` could easily break your styles. There are browser inconsistencies.

Also according to the [spec](https://www.w3.org/TR/css-cascade-3/#cascade-origin), adding `!impotant` to `animation` is unnecessary most of the time because of the origin cascading.

If you care about old browsers, adding `!impotant` to `animation` is probably not a good idea. If not, consider using shadow dom or web components instead.

**Comment by scherbenokk** [comment]
@crimx agreed. I will think about how not to break changes. What do you think about additional flag to options? (aka clearDefaults: true or something similar)?

**Comment by crimx** [comment]
Yeah I was thinking about the same thing. That would work.

**Comment by scherbenokk** [comment]
@crimx updated PR. Could you please check, is it ok?

**Comment by crimx** [comment]
Thanks for the PR! Published.

**Comment by scherbenokk** [comment]
Thank you)

**Pull request merged**
